"""empty message

Revision ID: 13f5a9da9ace
Revises: f39519f309d3
Create Date: 2019-05-18 18:24:49.986842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f5a9da9ace'
down_revision = 'f39519f309d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_time', sa.Column('alive', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_time', 'alive')
    # ### end Alembic commands ###
