"""empty message

Revision ID: 17d7444ca6fe
Revises: 1f7b88829d1c
Create Date: 2019-05-16 10:54:51.661529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d7444ca6fe'
down_revision = '1f7b88829d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_member_bind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('client_type', sa.String(length=20), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('openid', sa.String(length=80), nullable=True),
    sa.Column('unionid', sa.String(length=100), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_type_openid', 'oauth_member_bind', ['type', 'openid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_type_openid', table_name='oauth_member_bind')
    op.drop_table('oauth_member_bind')
    # ### end Alembic commands ###
