"""empty message

Revision ID: 1f7b88829d1c
Revises: 
Create Date: 2019-05-15 21:11:19.541907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7b88829d1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('salt', sa.String(length=32), nullable=True),
    sa.Column('reg_ip', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=64), nullable=True),
    sa.Column('login_name', sa.String(length=20), nullable=True),
    sa.Column('login_pwd', sa.String(length=32), nullable=True),
    sa.Column('login_salt', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('member')
    # ### end Alembic commands ###
