"""empty message

Revision ID: c442b0422737
Revises: dbb4e556def9
Create Date: 2019-05-18 20:41:08.814814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c442b0422737'
down_revision = 'dbb4e556def9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_time', sa.Column('close__time', sa.String(length=10), nullable=True))
    op.add_column('device_time', sa.Column('open__time', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_time', 'open__time')
    op.drop_column('device_time', 'close__time')
    # ### end Alembic commands ###
