"""empty message

Revision ID: dbb4e556def9
Revises: 13f5a9da9ace
Create Date: 2019-05-18 19:36:32.597507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb4e556def9'
down_revision = '13f5a9da9ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_time', sa.Column('period', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_time', 'period')
    # ### end Alembic commands ###
